/-
  exp/CESLongVolPayoff.lean — η-CES long-volatility trader payoff
  (Bregman with f(x) = x^{1/(1-η)}, the marginal-price-impact exponent).

  Paired with the Plank-side `CESLongPayoff.plk`. The first formal
  exercise: define π_η and prove that π_{1/2} (already defined and
  reasoned about in `exp.eta`) is the η = 1/2 specialization, under the
  EVM constraint (we keep Plank's η=1/2 swap formulas for Δ^O and
  P_post; only the distance function deforms with η).
-/
import Mathlib
import exp.eta

open Real
open scoped BigOperators

namespace CFMM.Eta

/-- **η-CES trader payoff (long-vol, Bregman form).**

    Defined as the Bregman divergence generated by `f(x) = x^{1/(1-η)}`
    (the η-CES marginal-price-impact exponent we derived from
    `slippage_residual`), evaluated on the trade pair
    `(a, b) = (P_{1/2}(i)·Δ^I, Δ^O)` where Δ^O comes from Plank's
    η=1/2 swap (`Delta_O_half`):

        π_η^{trader} = a^p − b^p − p · b^q · (a − b),
                       p = 1/(1−η),  q = η/(1−η).

    At η = 1/2: p = 2, q = 1, so the formula collapses to
    `a² − b² − 2b(a−b) = (a−b)²` = `pi_trader_half`. -/
noncomputable def pi_eta_trader
    (η lam Δi : ℝ) (i : Int) (L_bar Delta_I : ℝ) : ℝ :=
  let a := P_half lam Δi i * Delta_I
  let b := Delta_O_half lam Δi i L_bar Delta_I
  let p : ℝ := 1 / (1 - η)
  let q : ℝ := η / (1 - η)
  a ^ p - b ^ p - p * b ^ q * (a - b)

/-- **π_{1/2} is the η = 1/2 specialization of π_η.**

    Direct algebraic specialization: at η = 1/2 the Bregman exponents
    are p = 2 and q = 1, so

        π_η(1/2) = a² − b² − 2b(a−b) = (a−b)² = π_{1/2}^trader.

    Hypotheses: `0 < lam` to keep `P_half lam Δi i > 0` (positivity for
    the rpow at non-integer exponents in the general definition; at
    η = 1/2 the exponents reduce to natural numbers so positivity is
    not strictly load-bearing, but kept for compatibility with the
    general statement). -/
theorem pi_eta_extends_half
    (lam : ℝ) (hlam : 0 < lam)
    (Δi : ℝ) (i : Int) (L_bar Delta_I : ℝ) :
    pi_eta_trader (1/2) lam Δi i L_bar Delta_I
      = pi_trader_half lam Δi i L_bar Delta_I := by
  sorry

end CFMM.Eta
